CREATE TABLE `s71_challenge` (
  `RecID` int NOT NULL AUTO_INCREMENT,
  `Value` varchar(100) NOT NULL,
  PRIMARY KEY (`RecID`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
